# Display a box
print("##########")
print("#        #")
print("#        #")
print("##########")
print("\n")
print("##########")
print("#  *  *  #")
print("#    w   #")
print("#   __   #")
print("##########")