print("what is your name human?")
input()
print("\n")
print("How old are you (in years)?")
whole_number = int(input())
print("\n")
print("How tall are you (in meters)?")
decimal_number = float(input())
print("\n")
print("How much do you weigh (in kilograms)?")
whole_number = int(input())
print("\n")

print("you are {input()} years old and your bmi is")
